import { Router, static as serveStatic } from 'express';
import { fileURLToPath } from 'node:url';

const traditions = [['Protestant', '개신교'], ['Catholic', '가톨릭'], ['Buddhism', '불교'], ['Judaism', '유대교'], ['Islam', '이슬람'], ['Hinduism', '힌두교'], ['Confucianism', '유교']];
const escape = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const link = (href, label, secondary = false) => `<a class="button${secondary ? ' secondary' : ''}" href="${href}">${label}<span aria-hidden="true">↗</span></a>`;
const paths = () => `<div class="tradition-grid">${traditions.map(([en, ko]) => `<article class="tradition-card"><span class="path-light" aria-hidden="true"></span><h3>${ko}</h3><p lang="en">${en}</p></article>`).join('')}</div>`;
const heading = (tag, title, text) => `<div class="section-heading"><p class="eyebrow">${tag}</p><h2>${title}</h2><p>${text}</p></div>`;
const about = () => `<section class="section split">${heading('A LIGHT WITHIN', '답을 서두르지 않는 공간', '마음에는 하나의 정답보다, 자신의 이야기를 꺼낼 시간이 필요할 때가 있습니다.')}<div class="prose"><p>ONARIA는 오늘의 감정을 살펴보고, 대화와 기록을 통해 나를 돌아보는 마음 성찰 서비스입니다.</p><p>서로 다른 삶과 신앙을 존중합니다. 어떤 길을 선택하든, 판단보다 경청이 먼저인 경험을 지향합니다.</p><a class="text-link" href="/about">ONARIA 알아보기 <span aria-hidden="true">→</span></a></div></section>`;
const services = () => `<section class="section">${heading('SMALL MOMENTS, MEANINGFUL CHANGE', '오늘의 나를 만나는 방법', '거창한 결심 없이, 지금 느끼는 마음에서 시작하세요.')}<div class="cards"><article><span class="step">01 / CONVERSATION</span><h3>AI 마음대화</h3><p>오늘의 감정을 고르고, 글이나 음성으로 마음을 표현합니다. 짧은 질문을 따라 자신의 생각을 살펴볼 수 있습니다.</p></article><article><span class="step">02 / REFLECTION</span><h3>지혜와 함께하는 성찰</h3><p>현재 앱에서는 성경 구절을 읽고 묵상을 이어갈 수 있습니다. 전통별 경험은 검토와 확장 중입니다.</p></article><article><span class="step">03 / A MOMENT FOR YOU</span><h3>마음 챙김과 기록</h3><p>대화에서 발견한 마음과 작은 실천을 카드에 담아, 필요할 때 다시 돌아봅니다.</p></article></div></section>`;
const seven = () => `<section class="section traditions">${heading('SEVEN PATHS. EQUAL RESPECT.', '다른 길, 같은 존중', '일곱 전통을 동등하게 존중합니다. 각 전통의 출처와 맥락을 지키며 경험을 준비합니다.')}${paths()}<p class="note">현재 성경 기반의 말씀 기능을 제공하며, 다른 전통의 콘텐츠와 선택 경험은 검토 중입니다. 일곱 전통 모두가 정식 서비스로 제공되는 단계는 아닙니다.</p></section>`;
const safety = () => `<section class="section split soft">${heading('CARE COMES FIRST', '마음의 안전을 먼저 생각합니다', 'AI의 역할과 한계를 분명히 하고, 필요한 순간에는 현실의 도움을 우선합니다.')}<div class="prose"><h3>전문가를 대신하지 않습니다</h3><p>ONARIA의 대화는 자기 성찰을 돕기 위한 것으로, 의료적 진단·치료·전문 상담을 제공하지 않습니다.</p><h3>개인적인 이야기를 조심스럽게</h3><p>운영 화면의 안전 현황은 위험 수준과 분류별 집계로 표시합니다. 민감한 대화 원문을 기본 표시하지 않습니다.</p><a class="text-link" href="/privacy">개인정보 처리 안내 <span aria-hidden="true">→</span></a></div></section>`;
const apps = () => `<section class="section app-section" id="apps"><div>${heading('ONARIA APPS', '당신의 속도로, 당신의 곁에', '모바일 앱은 현재 테스트와 개선을 진행하고 있습니다. 공식 다운로드 링크는 공개 준비가 끝난 뒤 안내합니다.')}<p class="availability">Android · 테스트 중 <span aria-hidden="true">/</span> iOS · 공개 준비 중</p></div><div class="app-art" aria-hidden="true"><img src="/assets/onaria-emblem.svg" width="180" height="180" loading="lazy" alt=""><span>ONARIA</span><p>EVERY HEART HAS ITS OWN WAY</p></div></section>`;
const cta = () => `<section class="cta"><p class="eyebrow">YOUR WAY, AT YOUR PACE</p><h2>지금의 마음에서<br>시작해도 괜찮습니다.</h2>${link('/services', 'ONARIA 경험 살펴보기')}</section>`;
const pages = {
  '/': { title: 'ONARIA | 모든 마음에는 저마다의 길이 있습니다', description: '오늘의 감정을 살피는 AI 마음대화와 기록. 서로 다른 길을 존중하는 마음 성찰 서비스 ONARIA.', body: () => `<section class="hero"><div class="hero-copy"><p class="eyebrow">A QUIET SPACE FOR YOUR INNER LIGHT</p><p class="wordmark">ONARIA</p><h1>모든 마음에는<br>저마다의 길이 있습니다.</h1><p class="hero-english" lang="en">EVERY HEART HAS ITS OWN WAY</p><div class="hero-actions">${link('/services', '마음의 여정 알아보기')}${link('/#apps', '앱 소식 보기', true)}</div><p class="hero-note">잠시 머물러도 괜찮은, 당신을 위한 공간.</p></div><div class="hero-art"><img src="/assets/onaria-emblem.svg" width="460" height="460" fetchpriority="high" alt="하나의 빛 주위를 둘러싼 일곱 길, ONARIA 심볼"><span class="orbit-label">SEVEN PATHS · ONE INNER LIGHT</span></div><a class="scroll-cue" href="#introduction">천천히 알아보기 <span aria-hidden="true">↓</span></a></section><div id="introduction">${about()}</div>${services()}${seven()}<section class="section">${heading('HOW IT FLOWS', '마음에 닿는 작은 순서', '대화를 끝까지 채우지 않아도 괜찮습니다. 원하는 만큼 머무르세요.')}<ol class="flow"><li><span>01</span><h3>마음을 고르고</h3><p>오늘 느끼는 감정과 강도를 살펴봅니다.</p></li><li><span>02</span><h3>이야기를 나누고</h3><p>짧은 질문에 나의 속도로 답합니다.</p></li><li><span>03</span><h3>작은 발견을 담아요</h3><p>마음 카드와 작은 실천으로 돌아봅니다.</p></li></ol></section>${safety()}${apps()}${cta()}` },
  '/about': { title: 'ONARIA 소개', description: '서로 다른 마음과 길을 존중하는 ONARIA의 방향.', body: () => `${pageHero('ABOUT ONARIA', '나를 이해하는 시간,<br>서로를 존중하는 마음.', '다름을 하나의 답으로 바꾸려 하지 않습니다.')}${about()}<section class="section"><div class="cards"><article><h2>경청</h2><p>마음을 서둘러 해석하거나 단정하지 않는 대화를 지향합니다.</p></article><article><h2>다양성</h2><p>신앙과 삶의 배경이 서로 다를 수 있음을 존중합니다.</p></article><article><h2>작은 실천</h2><p>오늘 할 수 있는 작은 행동과 성찰에 집중합니다.</p></article></div></section>${cta()}` },
  '/services': { title: 'ONARIA 서비스', description: 'AI 마음대화, 성찰과 마음 기록. 현재 구현 범위와 앱 준비 상태를 안내합니다.', body: () => `${pageHero('THE ONARIA EXPERIENCE', '마음을 말하고,<br>나를 돌아보는 경험.', '현재 모바일 앱을 테스트하며 흐름을 다듬고 있습니다.')}${services()}${safety()}${apps()}` },
  '/traditions': { title: '일곱 전통 | ONARIA', description: '개신교, 가톨릭, 불교, 유대교, 이슬람, 힌두교, 유교. 동등한 존중과 출처에 대한 책임.', body: () => `${pageHero('SEVEN PATHS', '길은 달라도,<br>존중은 같습니다.', '전통을 섞어 하나의 교리로 제시하지 않습니다.')}${seven()}<section class="section prose"><h2>맥락과 출처를 지키는 원칙</h2><p>검색 가능한 자료와 검토된 근거를 바탕으로 성찰을 돕는 방향을 지향합니다. 이 페이지에서는 새로운 경전 인용이나 교리 해석을 제공하지 않습니다.</p><p>AI의 설명은 해당 종교 기관이나 전문가의 공식 입장을 대변하지 않습니다.</p></section>` },
  '/privacy': { title: '개인정보 처리 안내 | ONARIA', description: 'ONARIA의 현재 데이터 처리 구조와 출시 전 확정할 사항을 안내합니다.', body: () => legal('개인정보 처리 안내', `<p class="notice">현재 구현을 설명하는 사전 안내입니다. 정식 서비스 공개 전 운영 주체, 문의처, 보유 기간과 국외 이전 등 적용 사항을 확정한 개인정보 처리방침으로 검토·게시해야 합니다.</p><h2>어떤 정보가 처리되나요?</h2><p>마음대화 사용 시 입력한 내용과 최근 대화 맥락이 응답 생성을 위해 서버에 전달됩니다. 회원가입 기능을 사용하는 경우 이름, 휴대폰 번호와 선택 입력 정보를 회원 DB에 보관합니다. 저장한 마음 카드 등 일부 기록은 기기에 보관됩니다.</p><h2>AI와 안전 처리</h2><p>서버에서 외부 AI를 활성화한 경우 필요한 대화 맥락이 AI 제공자에게 전달됩니다. 외부 AI 사용 여부와 제공 범위는 운영 설정에 따라 달라집니다. 서비스는 전문적인 진단이나 치료를 대신하지 않습니다.</p><h2>운영 정보</h2><p>AI 사용량에는 토큰 수, 비용 추정치와 가명화된 식별자가 포함될 수 있습니다. 안전 운영 화면에는 위험 수준·분류·시간과 집계를 표시하며 대화 원문을 기본 표시하지 않습니다.</p><h2>웹사이트와 관리자 쿠키</h2><p>이 공개 홈페이지는 광고 추적 도구를 포함하지 않습니다. 관리자 로그인에는 최대 30분 유효한 필수 세션 쿠키를 사용합니다. 관리자 API 응답은 오프라인 캐시에 저장하지 않습니다.</p><h2>이용자 권리와 문의</h2><p>개인정보 열람·정정·삭제 요청을 받을 운영 문의처와 처리 절차는 정식 공개 전 확정이 필요합니다. 공개 안내가 완료되기 전에는 홈페이지에서 회원 정보나 문의 내용을 수집하지 않습니다.</p>`) },
  '/terms': { title: '이용 안내 | ONARIA', description: 'ONARIA 테스트 서비스의 범위와 AI 성찰 서비스의 한계를 안내합니다.', body: () => legal('이용 안내', `<p class="notice">정식 이용약관 확정 전 사전 안내입니다. 계약 주체, 이용 대상, 책임 범위와 분쟁 처리 등은 운영 검토 후 정식 약관에 명시해야 합니다.</p><h2>서비스의 목적</h2><p>ONARIA는 감정 표현과 자기 성찰을 돕는 서비스입니다. 의료적 진단·치료, 전문 상담 또는 종교 기관의 공식 자문을 제공하지 않습니다.</p><h2>현재 제공 범위</h2><p>모바일 앱은 테스트와 개선 중입니다. 공개 홈페이지의 소개는 모든 플랫폼이나 전통의 정식 출시를 의미하지 않습니다. 공식 다운로드와 이용 조건은 준비 후 안내합니다.</p><h2>AI 응답의 한계</h2><p>AI 응답에는 오류가 있을 수 있습니다. 중요한 결정은 신뢰할 수 있는 전문가와 확인해 주세요. 긴급한 위험이 있는 경우 앱의 답변을 기다리기보다 현실의 긴급 지원을 우선해 주세요.</p><h2>이용 시 배려</h2><p>타인의 개인정보나 공개 권한이 없는 민감한 자료를 입력하지 마세요. 서비스의 안전 장치와 다른 이용자의 권리를 존중해 주세요.</p>`) },
};
function pageHero(tag, title, text) { return `<section class="page-hero"><p class="eyebrow">${tag}</p><h1>${title}</h1><p>${text}</p></section>`; }
function legal(title, body) { return `${pageHero('SERVICE INFORMATION', title, '현재 구현 기준 · 정식 공개 전 검토 필요')}<article class="section legal prose">${body}</article>`; }

export function websiteRouter({ publicOrigin }) {
  const router = Router();
  const parsed = new URL(publicOrigin);
  if (!['https:', 'http:'].includes(parsed.protocol) || parsed.username || parsed.password) throw new Error('Invalid PUBLIC_ORIGIN');
  const origin = parsed.origin;
  router.use('/assets', serveStatic(fileURLToPath(new URL('../public/website', import.meta.url)), { maxAge: '1h', dotfiles: 'deny' }));
  router.get('/robots.txt', (_req, res) => res.type('text').send(`User-agent: *\nAllow: /\nDisallow: /admin\nDisallow: /v1/\nSitemap: ${origin}/sitemap.xml\n`));
  router.get('/sitemap.xml', (_req, res) => res.type('application/xml').send(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${Object.keys(pages).map(path => `<url><loc>${escape(origin + path)}</loc></url>`).join('')}</urlset>`));
  for (const [path, page] of Object.entries(pages)) router.get(path, (_req, res) => {
    const canonical = escape(origin + path);
    res.set('Cache-Control', 'public, max-age=60');
    res.type('html').send(`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(page.title)}</title><meta name="description" content="${escape(page.description)}"><meta name="robots" content="index,follow"><meta name="theme-color" content="#10182b"><link rel="canonical" href="${canonical}"><meta property="og:type" content="website"><meta property="og:locale" content="ko_KR"><meta property="og:site_name" content="ONARIA"><meta property="og:title" content="${escape(page.title)}"><meta property="og:description" content="${escape(page.description)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${escape(origin)}/assets/social-preview.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/assets/onaria-emblem.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/site.css"><script src="/assets/site.js" defer></script></head><body><a class="skip-link" href="#main">본문 바로가기</a><header class="site-header"><a class="brand" href="/" aria-label="ONARIA 홈"><img src="/assets/onaria-emblem.svg" width="42" height="42" alt=""><span>ONARIA</span></a><button class="menu-button" type="button" aria-expanded="false" aria-controls="site-nav">메뉴 <span aria-hidden="true">☰</span></button><nav id="site-nav" aria-label="주 메뉴"><a href="/about"${path === '/about' ? ' aria-current="page"' : ''}>ONARIA 소개</a><a href="/services"${path === '/services' ? ' aria-current="page"' : ''}>서비스</a><a href="/traditions"${path === '/traditions' ? ' aria-current="page"' : ''}>일곱 전통</a><a class="nav-cta" href="/#apps">앱 소식 <span aria-hidden="true">↗</span></a></nav></header><main id="main">${page.body()}</main><footer class="site-footer"><div><a class="brand" href="/">ONARIA</a><p>모든 마음에는 저마다의 길이 있습니다.</p><small>EVERY HEART HAS ITS OWN WAY</small></div><nav aria-label="하단 메뉴"><a href="/about">소개</a><a href="/services">서비스</a><a href="/privacy">개인정보 처리 안내</a><a href="/terms">이용 안내</a></nav><p class="copyright">© ONARIA · 마음의 속도를 존중합니다.</p></footer></body></html>`);
  });
  return router;
}
